### ISSUE TITLE
Custom game

### ISSUE THREAD

**Issue by otherwise33** [HerrEurobeat/steam-idler#5]
Hi, i leave brackets empty but it says custom game in steam what am i missing?
![1](https://user-images.githubusercontent.com/111538512/212780864-6dde7350-8c45-481a-9efc-004866d613f4.png)
![2](https://user-images.githubusercontent.com/111538512/212780867-24d1ac69-e9b2-474f-a6bb-6db4f1c61918.png)

**Comment by otherwise33** [comment]
Also another error: 
![image](https://user-images.githubusercontent.com/111538512/212918821-2636be61-be47-4ad4-be82-0150e59161c6.png)
How can i fix it?

**Comment by HerrEurobeat** [comment]
Hey, sorry for the late response.  
I'm not sure why leaving the custom game empty still causes "In non-Steam game" to be shown, that shouldn't happen afaik. I would need to look into that further.  
  
Regarding the relog:  
That's not an error, the account just temporarily lost the internet connection to Steam. That can happen from time to time, nothing to worry about as the script relogs your accounts after a few seconds.  
I assume your account "jeffcramer8o" uses mobile steam guard and that's why the script asked for the code again as it can't use the cached token for mobile steam guard, that only works for email steam guard.

**Comment by otherwise33** [comment]
Hi, thank you for replying. None of my accounts uses Steam Mobile Guard but sometimes it asking for guard code. Im hourboosting 200 accounts in my VDS but i got a big problem.
![image](https://user-images.githubusercontent.com/111538512/215109154-9b9a3b42-fcd5-46b7-9dea-2182e32bea85.png)
Every time i checked the vds, i saw this problem. Before you updated the bot, it was closing itself when it got errors so i was using commend prompt with this codes: echo off
cls
:a
node idler.js
goto a
pause 

But i can make it this with newer version because it doesnt closes itself. How can i make the bot restart itself when it got errors?

**Comment by otherwise33** [comment]
![image](https://user-images.githubusercontent.com/111538512/215357738-64ffd73e-7f2a-41f9-9a34-6aa0163cfc7a.png)
I need help...

**Comment by HerrEurobeat** [comment]
Hey, sorry for the late response, I wasn't at home the past week.  
The bot was previously crashing when loosing connection which I fixed by adding a relog system.  
All the accounts in your screenshot which have lost connection because of an unstable internet connection should get relogged after 15 seconds.  
  
The relog process in your second screenshot however is blocked by a pending steam guard code request.  
I have sadly no idea why it is asking for one if your account does not use mobile steam guard as it should use the cached token. Since the relog system is copied from my steam-comment-service-bot it should however work, no idea atm.  
  
I have very little time atm but I'll see if I manage to look into it more sometime in the next few days.

**Comment by HerrEurobeat** [comment]
Hey, long time no see.  
Regarding the custom game status: I have clarified in the README that you must not pass a String as the first argument when you don't want to display any custom "non-steam" game instead of passing an empty string. This was apparently changed at some point and I didn't noticed that.

Furthermore regarding that relog issue: I might some changes (231d3ce & 357db53) to the login and relog system. Could you check if the issue still persists for you?

**Comment by brkee** [comment]
Error: Cannot find module 'output-logger'
help pls
